worker:
  build: .
  dockerfile: Dockerfile.worker
#  hostname: worker
  environment:
    MAX_CPU_CORES: 1
  links:
   - server

server:
  build: .
  dockerfile: Dockerfile.server
  hostname: server
  ports:
   - "5672:5672" # RabbitMQ
   - "6379:6379" # Redis
  environment:
    MAX_CPU_CORES: 1
    DT: 0.01
    T_MAX: 30
    THETA_RESOLUTION: 30
  volumes:
   - /tmp/results2:/results
